project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://ch1nv.github.io/luchinwei/
  title: "CHIN-WEI, LU"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - text: Notes
        menu:
          - href: notes/index.qmd
            text: All Notes
          - href: notes/tech/index.qmd
            text: Tech
          - href: notes/life/index.qmd
            text: Life
          - href: notes/reading/index.qmd
            text: Reading
          - href: notes/games/index.qmd
            text: Games
      - href: about.qmd
        text: About
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ch1nv
      - icon: github
        href: https://github.com/Ch1nv
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css



